esphome:
  name: wtc3-gateway
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.77.97
    gateway: 192.168.77.1
    subnet: 255.255.255.0

  ap:
    ssid: "WTC3-Gateway"
    password: "fallback_password"

captive_portal:

logger:

api:

ota:
  - platform: esphome
    password: !secret ota_password

uart:
  id: uart_modbus
  tx_pin: D7
  rx_pin: D6
  baud_rate: 9600
  parity: 'NONE'
  stop_bits: 1
  data_bits: 8

modbus:
  id: modbus1
  send_wait_time: 2000ms
  disable_crc: true

modbus_controller:
  - id: wtc3
    modbus_id: modbus1
    address: 1
    setup_priority: -10

text_sensor:
  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Central HVAC state"
    id: water_inlet_temperature
    register_type: holding
    address: 4135
    raw_encode: HEXBYTES
    lambda: |-
      uint16_t value = modbus_controller::word_from_hex_str(x, 0);
      switch (value) {
        case 0: return std::string("initializing");
        case 1: return std::string("heating");
        case 2: return std::string("cooling");
        case 3: return std::string("maintenance");
        default: return std::string("unknown");
      }

sensor:
  # ROOM 1

  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 1 Temperature"
    id: room1_temperature
    register_type: holding
    address: 4136
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 1 Humidity"
    id: room1_humidity
    register_type: holding
    address: 4137
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 1 Dew Point"
    id: room1_dewpoint
    register_type: holding
    address: 4138
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # ROOM 2

  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 2 Temperature"
    id: room2_temperature
    register_type: holding
    address: 4142
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 2 Humidity"
    id: room2_humidity
    register_type: holding
    address: 4143
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 2 Dew Point"
    id: room2_dewpoint
    register_type: holding
    address: 4144
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # ROOM 3

  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 3 Temperature"
    id: room3_temperature
    register_type: holding
    address: 4148
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 3 Humidity"
    id: room3_humidity
    register_type: holding
    address: 4149
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 3 Dew Point"
    id: room3_dewpoint
    register_type: holding
    address: 4150
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # ROOM 4

  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 4 Temperature"
    id: room4_temperature
    register_type: holding
    address: 4154
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 4 Humidity"
    id: room4_humidity
    register_type: holding
    address: 4155
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 4 Dew Point"
    id: room4_dewpoint
    register_type: holding
    address: 4156
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

switch:
  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 1 Comfort Mode"
    id: room1_comfort_mode
    register_type: coil
    address: 4605
    bitmask: 0x01
  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 2 Comfort Mode"
    id: room2_comfort_mode
    register_type: coil
    address: 4613
    bitmask: 0x01
  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 3 Comfort Mode"
    id: room3_comfort_mode
    register_type: coil
    address: 4621
    bitmask: 0x01
  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 4 Comfort Mode"
    id: room4_comfort_mode
    register_type: coil
    address: 4629
    bitmask: 0x01

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 1 Calling for Heat"
    id: valve_1
    register_type: coil
    address: 4112
  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 2 Calling for Heat"
    id: valve_2
    register_type: coil
    address: 4113
  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 3 Calling for Heat"
    id: valve_3
    register_type: coil
    address: 4114
  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 4 Calling for Heat"
    id: valve_4
    register_type: coil
    address: 4115
  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Pump Operation"
    id: pump
    register_type: coil
    address: 4119



number:
  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 1 Setpoint Temperature"
    id: room1_setpoint
    register_type: holding
    address: 4604
    unit_of_measurement: "°C"
    min_value: 17
    max_value: 29
    step: 1
    mode: SLIDER
    lambda: |-
      return x + 17;
    write_lambda: |-
      return x - 17;
  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 2 Setpoint Temperature"
    id: room2_setpoint
    register_type: holding
    address: 4605
    unit_of_measurement: "°C"
    min_value: 17
    max_value: 29
    step: 1
    mode: SLIDER
    lambda: |-
      return x + 17;
    write_lambda: |-
      return x - 17;
  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 3 Setpoint Temperature"
    id: room3_setpoint
    register_type: holding
    address: 4606
    unit_of_measurement: "°C"
    min_value: 17
    max_value: 29
    step: 1
    mode: SLIDER
    lambda: |-
      return x + 17;
    write_lambda: |-
      return x - 17;
  - platform: modbus_controller
    modbus_controller_id: wtc3
    name: "Room 4 Setpoint Temperature"
    id: room4_setpoint
    register_type: holding
    address: 4607
    unit_of_measurement: "°C"
    min_value: 17
    max_value: 29
    step: 1
    mode: SLIDER
    lambda: |-
      return x + 17;
    write_lambda: |-
      return x - 17;
